// mitzlolClient/react-client/src/components/wordGrouping/wordGrouping.tsx
import React from "react";
import { useSelector } from "react-redux";
import { If, Then } from "react-if-elseif-else-render";
import { ApplicationState } from "../../store";
import { Container, Row, Col, Card } from "react-bootstrap";
import "./wordGrouping.css";

const WordGrouping = () => {
  const isWaiting = useSelector((state: ApplicationState) => {
    return state.mitzlol.loading;
  });
  const total = useSelector((state: ApplicationState) => state.mitzlol.total);
  const mitzlolim = useSelector(
    (state: ApplicationState) => state.mitzlol.mitzlolim
  );
  return (
    <div>
      <If condition={!isWaiting}>
        <Then>
          <Container fluid>
            <If condition={total === 0}>
              <Then>
                <Row className="justify-content-md-center">
                  <Col md="8" style={{ marginTop: "10px" }}>
                    <Card>
                      <Card.Body>
                        <Card className="my-2">
                          <Card.Header>לא נמצאו תוצאות</Card.Header>
                        </Card>
                      </Card.Body>
                    </Card>
                  </Col>
                </Row>
              </Then>
            </If>
            <If condition={total > 0}>
              <Then>
                {mitzlolim.map((wordGroup: any, i: number) => (
                  <If key={i} condition={wordGroup.words.length}>
                    <Then>
                      <Row className="justify-content-md-center">
                        <Col md="8" className="word-grouping">
                          <Card>
                            <Card.Body>
                              <Card className="my-2">
                                <Card.Header>{wordGroup.title}</Card.Header>
                                <Card.Body>
                                  <Card.Text>
                                    {wordGroup.words.join(", ")}
                                  </Card.Text>
                                </Card.Body>
                              </Card>
                            </Card.Body>
                          </Card>
                        </Col>
                      </Row>
                    </Then>
                  </If>
                ))}
              </Then>
            </If>
          </Container>
        </Then>
      </If>
    </div>
  );
};

export default WordGrouping;

// mitzlolClient/src/components/wordGrouping.vue
<template>
    <div v-if="!$store.state.waiting">
        <div class="container-fluid" >
            <div v-if="$store.state.total == 0">
                <div class="row justify-content-md-center">
                    <div class="col-12 col-md-8" style="margin-top: 10px;">
                        <div class="card" >
                            <div class="card-body" style="padding-bottom: 10px;">
                                <div class="card my-2">
                                    <div class="card-header">
                                        {{ "לא נמצאו תוצאות" }}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div v-if="$store.state.total > 0">
                <div v-for="wordGroup in $store.state.mitzlolim" :key="wordGroup.id">
                    <div v-if="wordGroup.words.length">
                        <div class="row justify-content-md-center">
                            <div class="word-grouping col-12 col-md-8">
                                <div class="card">
                                    <div class="card-body">
                                        <div class="card my-2">
                                            <div class="card-header">
                                                {{ wordGroup.title }}
                                            </div>
                                            <div class="card-body">
                                                <p class="card-text">
                                                    {{ wordGroup.words.join(', ') }}
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>
<script>
export default {
  name: "wordGrouping"
};
</script>

<style scoped>
.card-body .card-text {
  text-align: right;
} 
.card-body {
    width: 100%;
}
.word-grouping {
    margin-bottom: 10px;
}
</style>
