// mitzlolClient/vue-client/src/components/searchBox.vue
<template>
    <div class="container-fluid search-box-container">
        <div class="row justify-content-center">
			<span class="logo">מִצְלוֹל</span>
        </div>
        <div class="row justify-content-md-center">
            <div class="col-12 col-md-6">
                <input type="text" class="input form-control search-box" v-on:keyup="getWords" v-model="word" />
            </div>
        </div>
    </div>
</template>
<script>
export default {
	name: "searchBox",
	data() {
		return {
			word: ""
		};
	},
	methods: {
		getWords: function(e) {
			if (e.keyCode === 13) {
				this.$store.dispatch("getMitzlolimAsync", this.word);
			}
		}
	}
};
</script>
<style scoped>
.search-box-container {
	padding-top: 100px;
}
.logo {
	font-family: Narkisim;
    font-size: 100px;
    color: #b353b5;
}
.search-box {
	direction: rtl; 
	box-shadow: rgba(0, 0, 0, 0.16) 0px 2px 2px 0px, rgba(0, 0, 0, 0.08) 0px 0px 0px 1px;
	margin-bottom: 30px;
}
</style>

// mitzlolClient/react-client/src/components/searchBox/searchBox.tsx
import React from "react";
import { useDispatch } from "react-redux";
import "./searchBox.css";

import * as THUNK_ACTIONS_CREATORS from "../../store/actions/thunk";
import { Dispatch } from "redux";
import { Container, Row, Col, FormControl } from "react-bootstrap";

const SearchBox = () => {
  const dispatch = useDispatch();
  return (
    <Container fluid className="search-box-container">
      <Row className="justify-content-center">
        <span className="logo">מִצְלוֹל</span>
      </Row>
      <Row className="justify-content-md-center">
        <Col md="6">
          <FormControl
            as="input"
            type="text"
            className="input form-control search-box"
            onKeyUp={(e: React.KeyboardEvent<HTMLInputElement>) =>
              getWords(e, dispatch)
            }
          />
        </Col>
      </Row>
    </Container>
  );
};

function getWords(
  e: React.KeyboardEvent<HTMLInputElement>,
  dispatch: Dispatch<any>
) {
  if (e.keyCode === 13) {
    dispatch(
      THUNK_ACTIONS_CREATORS.thunkGetMitzlolim(
        (e.currentTarget as HTMLInputElement).value
      )
    );
  }
}

export default SearchBox;
