// mitzlolClient/vue-client/src/components/spinner.vue
<template>
    <div v-if="$store.state.waiting">
        <div class="container-fluid" >
            <div class="row justify-content-md-center">
                <div class="col-12 col-md-8">
                    <div class="card" >
                        <div class="card-body">
                            <div class="card my-2">
                                <div class="card-header">
                                    <!-- hourglass -->
                                    <span>&#8987;</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>
<script>
export default {
	name: "spinner",
};
</script>
<style scoped>
.card-body .card-text {
	text-align: right;
}
</style>

// mitzlolClient/react-client/src/components/spinner/spinner.tsx
import React from "react";
import { useSelector } from "react-redux";
import { If, Then } from "react-if-elseif-else-render";
import { ApplicationState } from "../../store";
import { Container, Row, Col, Card } from "react-bootstrap";

const Spinner = () => {
  const isWaiting = useSelector(
    (state: ApplicationState) => state.mitzlol.loading
  );
  return (
    <div>
      <If condition={isWaiting}>
        <Then>
          <Container fluid>
            <Row className="justify-content-md-center">
              <Col className="col-md-8">
                <Card>
                  <Card.Body>
                    <Card className="my-2">
                      <Card.Header>
                        {/* hourglass */}
                        <span>&#8987;</span>
                      </Card.Header>
                    </Card>
                  </Card.Body>
                </Card>
              </Col>
            </Row>
          </Container>
        </Then>
      </If>
    </div>
  );
};
export default Spinner;
